name: Notion Blogger
on:
  workflow_dispatch:
    

jobs:
  notion-blogger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notion Blogger
        uses: ./
        with:
          SERVICE_API_KEYS: '{"dev": "secret"}'
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE: ${{ secrets.NOTION_DATABASE }}